name: Node.js CI Workflow

# Trigger this workflow on push or pull request events
on:
  push:
    branches:
      - main  # Change to the branch you want, e.g., 'main', 'master', etc.
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # GitHub will handle Node.js 20 transition here

      - name: Set up Node.js environment (use Node.js 20)
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Explicitly specify Node.js 20

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Verify Node.js version
        run: node -v  # Optional: Verify Node.js version in logs
