jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clear npm cache
        run: npm cache clean --force

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Verify Node.js version
        run: node -v
