jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # No change needed here for Node.js 20

      - name: Set up Node.js environment (use Node.js 20)
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Explicitly set Node.js version 20
